"""BPMN 2.0 data models for process modeling and evaluation.

This module contains the core data structures for BPMN elements and results,
used across different agent implementations and evaluation pipelines.
"""

from pydantic import BaseModel
from typing import List, Dict, Any, Optional, Union


class RetrievalResult(BaseModel):
    """Result from retrieval agent."""
    documents: List[str]
    metadatas: List[Dict[str, Any]]
    relevance_scores: List[float]


class ProcessElement(BaseModel):
    """A process element extracted from documents."""
    element_type: str  # "activity", "event", "gateway", "role", "decision", "parallel", etc.
    name: str
    description: str
    source_text: str  # Original text from document
    metadata: Dict[str, Any] = {}


class ProcessElementsResult(BaseModel):
    """Result from process element extraction."""
    elements: List[ProcessElement] = []  # Kept for backward compatibility
    process_name: str
    process_description: str = ""  # Primary output: process description
    confidence: float


class BPMNElement(BaseModel):
    """A BPMN 2.0 element."""
    element_type: str  # "pool", "lane", "activity", "event", "gateway", "sequence_flow"
    id: str
    name: str
    properties: Dict[str, Any] = {}
    source_elements: List[str] = []  # IDs of ProcessElements that led to this BPMN element
    lane: Optional[str] = None  # Lane ID for activities, events, and gateways


# ============================================================================
# Nested schema models (matching the LLM output format)
# ============================================================================

class DataObject(BaseModel):
    """Data object within a pool."""
    name: str
    type: str  # "data-file" or "data-store"


class Lane(BaseModel):
    """Lane within a pool."""
    name: str
    


class ProcessEvent(BaseModel):
    """Event in the process array or start/end event."""
    type: Optional[str] = None  # "event" or None for start/end events
    subType: Optional[str] = None  # "default", "messageSend", "messageReceive", "timer"
    name: str
    id: Optional[int] = None  # For message events linking (receive events)
    receiveEventId: Optional[int] = None  # For messageSend events: links to receive event id
    laneIndex: int = 0
    readDataObjectRefs: Optional[List[int]] = None
    writeDataObjectRefs: Optional[List[int]] = None
    documentation: Optional[str] = None  # Source documentation: "[Name (Seite X)]"


class ProcessTask(BaseModel):
    """Task in the process array."""
    type: str = "task"
    subType: str = "abstract"  # "abstract", "user", "service", etc.
    name: str
    laneIndex: int = 0
    readDataObjectRefs: Optional[List[int]] = None
    writeDataObjectRefs: Optional[List[int]] = None
    documentation: Optional[str] = None  # Source documentation: "[Name (Seite X)]"


# Forward reference for recursive structures
ProcessElementType = Union['ProcessTask', 'ProcessEvent', 'ProcessGateway']


class GatewayBranch(BaseModel):
    """Branch in a gateway."""
    label: Optional[str] = None
    branch: List[ProcessElementType] = []
    event: Optional[ProcessEvent] = None  # For event-based gateways


class ProcessGateway(BaseModel):
    """Gateway in the process array."""
    type: str  # "xor", "and", "or", "events-gateway"
    condition: Optional[str] = None  # For XOR gateways
    branches: List[GatewayBranch] = []
    laneIndex: int = 0
    documentation: Optional[str] = None  # Source documentation: "[Name (Seite X)]"


# Update the Union type after ProcessGateway is defined
ProcessElementType = Union[ProcessTask, ProcessEvent, ProcessGateway]
GatewayBranch.model_rebuild()
ProcessGateway.model_rebuild()


class Pool(BaseModel):
    """Pool containing lanes, process elements, and events."""
    name: str
    dataObjects: List[DataObject] = []
    lanes: List[Lane] = []
    startEvent: Optional[ProcessEvent] = None
    process: List[ProcessElementType] = []
    endEvent: Optional[Union[ProcessEvent, Dict[str, Any]]] = None


class BPMNModelJsonNested(BaseModel):
    """BPMN model in nested JSON format (as generated by LLM)."""
    pools: List[Pool]
    process_name: Optional[str] = None  # Optional top-level process name


# ============================================================================
# Flat BPMN format for validation (simplified structure)
# ============================================================================

class FlatBPMNElement(BaseModel):
    """Simplified BPMN element for validation purposes."""
    element_type: str  # "pool", "lane", "task", "event", "gateway"
    id: str  # Unique identifier that maps back to nested structure
    name: str
    lane: Optional[str] = None  # Lane name (if applicable)
    pool: Optional[str] = None  # Pool name (if applicable)
    parent_gateway: Optional[str] = None  # Gateway ID if element is inside a gateway branch
    branch_label: Optional[str] = None  # Branch label if element is inside a gateway branch
    order_index: Optional[int] = None  # Order within parent (for sequence)


class FlatBPMNModel(BaseModel):
    """Simplified flat BPMN model for validation."""
    elements: List[FlatBPMNElement]
    process_name: Optional[str] = None


__all__ = [
    "RetrievalResult",
    "ProcessElement",
    "ProcessElementsResult",
    "BPMNElement",
    # Nested BPMN models
    "DataObject",
    "Lane",
    "ProcessEvent",
    "ProcessTask",
    "ProcessGateway",
    "GatewayBranch",
    "Pool",
    "BPMNModelJsonNested",
    # Flat BPMN models
    "FlatBPMNElement",
    "FlatBPMNModel",
]
